# Generated by Django 5.2.15 on 2026-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('port', models.IntegerField(unique=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LOADING', 'Loading'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed')], default='LOADING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=255, unique=True)),
                ('local_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('DOWNLOADING', 'Downloading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DOWNLOADING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
