# Generated by Django 5.2.15 on 2026-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceinstance',
            name='port',
            field=models.IntegerField(),
        ),
    ]
