# Generated by Django 5.2.15 on 2026-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_alter_inferenceinstance_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceinstance',
            name='launch_mode',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=20),
        ),
    ]
