# Generated by Django 5.2.15 on 2026-06-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_add_inference_launch_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('INSTANCE', 'MLX instance'), ('ENDPOINT', 'Custom endpoint')], max_length=20)),
                ('endpoint_url', models.CharField(max_length=512)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_runs', to='orchestrator.inferenceinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
