# Generated by Django 5.2.15 on 2026-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_benchmarkrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceinstance',
            name='launch_mode',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MULTIMODAL', 'Multimodal'), ('EMBEDDING', 'Embedding')], default='TEXT', max_length=20),
        ),
    ]
