# Generated by Django 5.2.15 on 2026-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_alter_inferenceinstance_launch_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceinstance',
            name='launch_mode',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MULTIMODAL', 'Multimodal'), ('EMBEDDING', 'Embedding'), ('RERANKER', 'Reranker')], default='TEXT', max_length=20),
        ),
    ]
